# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: bionic

env:
  global:
    # this should already be set per https://docs.travis-ci.com/user/environment-variables/
    # and presumably was once set in older Travis versions but now we need it
    - TRAVIS_SECURE_ENV_VARS="true"

jobs:
  include:
    #- name: r-3.5
    #  env: R_VERSION="3.5"
    - name: r-4.0
      env: R_VERSION="4.0"

    
before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap
  # decrypt the file tests/cloud.json.enc file, cf https://docs.travis-ci.com/user/encrypting-files/
  # condition this on have secure environment variables which PRs off forks do not
  # cf https://docs.travis-ci.com/user/environment-variables/
  - if [[ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]]; then mkdir ~/.tiledb; openssl aes-256-cbc -K $encrypted_8fb10d0bb40b_key -iv $encrypted_8fb10d0bb40b_iv -in tests/cloud.json.enc -out ~/.tiledb/cloud.json -d; fi
  
install:
  - ./run.sh install_aptget r-cran-jsonlite r-cran-httr r-cran-r6 r-cran-base64enc r-cran-tinytest

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then ./run.sh run_tests; fi

after_failure:
  - ./run.sh dump_logs

#after_success:
#  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then ./run.sh coverage; fi

notifications:
  email:
    on_success: change
    on_failure: change

