# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ActivityEventType
#'
#' @description ActivityEventType Class
#'
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ActivityEventType <- R6::R6Class(
    "ActivityEventType",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)

            # MANUAL EDIT AFTER OPENAPI AUTOGEN
            .check_openapi_enum("ActivityEventType", val, .parse_ActivityEventType())

            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(ActivityEventTypeJson) {
            private$value <- jsonlite::fromJSON(ActivityEventTypeJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(ActivityEventTypeJson) {
            private$value <- jsonlite::fromJSON(ActivityEventTypeJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_ActivityEventType <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[read_schema, max_buffer_sizes, non_empty_domain, query_read, query_write, create, delete, register, deregister, udf, array_metadata_get, array_metadata_update, estimated_result_sizes]"
    )
    unlist(strsplit(res, ", "))
}


