# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayMetadata
#'
#' @description ArrayMetadata Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ranges  list( \link{ArrayMetadataEntry} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayMetadata <- R6::R6Class(
  'ArrayMetadata',
  public = list(
    `ranges` = NULL,
    initialize = function(
        `ranges`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`ranges`)) {
        stopifnot(is.vector(`ranges`), length(`ranges`) != 0)
        sapply(`ranges`, function(x) stopifnot(R6::is.R6(x)))
        self$`ranges` <- `ranges`
      }
    },
    toJSON = function() {
      ArrayMetadataObject <- list()
      if (!is.null(self$`ranges`)) {
        ArrayMetadataObject[['ranges']] <-
          lapply(self$`ranges`, function(x) x$toJSON())
      }

      ArrayMetadataObject
    },
    fromJSON = function(ArrayMetadataJson) {
      ArrayMetadataObject <- jsonlite::fromJSON(ArrayMetadataJson)
      if (!is.null(ArrayMetadataObject$`ranges`)) {
        self$`ranges` <- ApiClient$new()$deserializeObj(ArrayMetadataObject$`ranges`, "array[ArrayMetadataEntry]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ranges`)) {
        sprintf(
        '"ranges":
        [%s]
',
        paste(sapply(self$`ranges`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayMetadataJson) {
      ArrayMetadataObject <- jsonlite::fromJSON(ArrayMetadataJson)
      self$`ranges` <- ApiClient$new()$deserializeObj(ArrayMetadataObject$`ranges`, "array[ArrayMetadataEntry]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

