# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayInfoUpdate
#'
#' @description ArrayInfoUpdate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field description  character [optional]
#'
#' @field name  character [optional]
#'
#' @field uri  character [optional]
#'
#' @field access_credentials_name  character [optional]
#'
#' @field logo  character [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @field license_id  character [optional]
#'
#' @field license_text  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayInfoUpdate <- R6::R6Class(
  'ArrayInfoUpdate',
  public = list(
    `description` = NULL,
    `name` = NULL,
    `uri` = NULL,
    `access_credentials_name` = NULL,
    `logo` = NULL,
    `tags` = NULL,
    `license_id` = NULL,
    `license_text` = NULL,
    initialize = function(
        `description`=NULL, `name`=NULL, `uri`=NULL, `access_credentials_name`=NULL, `logo`=NULL, `tags`=NULL, `license_id`=NULL, `license_text`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!is.null(`access_credentials_name`)) {
        stopifnot(is.character(`access_credentials_name`), length(`access_credentials_name`) == 1)
        self$`access_credentials_name` <- `access_credentials_name`
      }
      if (!is.null(`logo`)) {
        stopifnot(is.character(`logo`), length(`logo`) == 1)
        self$`logo` <- `logo`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!is.null(`license_id`)) {
        stopifnot(is.character(`license_id`), length(`license_id`) == 1)
        self$`license_id` <- `license_id`
      }
      if (!is.null(`license_text`)) {
        stopifnot(is.character(`license_text`), length(`license_text`) == 1)
        self$`license_text` <- `license_text`
      }
    },
    toJSON = function() {
      ArrayInfoUpdateObject <- list()
      if (!is.null(self$`description`)) {
        ArrayInfoUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        ArrayInfoUpdateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`uri`)) {
        ArrayInfoUpdateObject[['uri']] <-
          self$`uri`
      }
      if (!is.null(self$`access_credentials_name`)) {
        ArrayInfoUpdateObject[['access_credentials_name']] <-
          self$`access_credentials_name`
      }
      if (!is.null(self$`logo`)) {
        ArrayInfoUpdateObject[['logo']] <-
          self$`logo`
      }
      if (!is.null(self$`tags`)) {
        ArrayInfoUpdateObject[['tags']] <-
          self$`tags`
      }
      if (!is.null(self$`license_id`)) {
        ArrayInfoUpdateObject[['license_id']] <-
          self$`license_id`
      }
      if (!is.null(self$`license_text`)) {
        ArrayInfoUpdateObject[['license_text']] <-
          self$`license_text`
      }

      ArrayInfoUpdateObject
    },
    fromJSON = function(ArrayInfoUpdateJson) {
      ArrayInfoUpdateObject <- jsonlite::fromJSON(ArrayInfoUpdateJson)
      if (!is.null(ArrayInfoUpdateObject$`description`)) {
        self$`description` <- ArrayInfoUpdateObject$`description`
      }
      if (!is.null(ArrayInfoUpdateObject$`name`)) {
        self$`name` <- ArrayInfoUpdateObject$`name`
      }
      if (!is.null(ArrayInfoUpdateObject$`uri`)) {
        self$`uri` <- ArrayInfoUpdateObject$`uri`
      }
      if (!is.null(ArrayInfoUpdateObject$`access_credentials_name`)) {
        self$`access_credentials_name` <- ArrayInfoUpdateObject$`access_credentials_name`
      }
      if (!is.null(ArrayInfoUpdateObject$`logo`)) {
        self$`logo` <- ArrayInfoUpdateObject$`logo`
      }
      if (!is.null(ArrayInfoUpdateObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ArrayInfoUpdateObject$`tags`, "array[character]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(ArrayInfoUpdateObject$`license_id`)) {
        self$`license_id` <- ArrayInfoUpdateObject$`license_id`
      }
      if (!is.null(ArrayInfoUpdateObject$`license_text`)) {
        self$`license_text` <- ArrayInfoUpdateObject$`license_text`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`uri`)) {
        sprintf(
        '"uri":
          "%s"
                ',
        self$`uri`
        )},
        if (!is.null(self$`access_credentials_name`)) {
        sprintf(
        '"access_credentials_name":
          "%s"
                ',
        self$`access_credentials_name`
        )},
        if (!is.null(self$`logo`)) {
        sprintf(
        '"logo":
          "%s"
                ',
        self$`logo`
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`license_id`)) {
        sprintf(
        '"license_id":
          "%s"
                ',
        self$`license_id`
        )},
        if (!is.null(self$`license_text`)) {
        sprintf(
        '"license_text":
          "%s"
                ',
        self$`license_text`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayInfoUpdateJson) {
      ArrayInfoUpdateObject <- jsonlite::fromJSON(ArrayInfoUpdateJson)
      self$`description` <- ArrayInfoUpdateObject$`description`
      self$`name` <- ArrayInfoUpdateObject$`name`
      self$`uri` <- ArrayInfoUpdateObject$`uri`
      self$`access_credentials_name` <- ArrayInfoUpdateObject$`access_credentials_name`
      self$`logo` <- ArrayInfoUpdateObject$`logo`
      self$`tags` <- ApiClient$new()$deserializeObj(ArrayInfoUpdateObject$`tags`, "array[character]", loadNamespace("tiledbcloud"))
      self$`license_id` <- ArrayInfoUpdateObject$`license_id`
      self$`license_text` <- ArrayInfoUpdateObject$`license_text`
      self
    }
  )
)

