# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayMetadata
#'
#' @description ArrayMetadata Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field entries  list( \link{ArrayMetadataEntry} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayMetadata <- R6::R6Class(
  'ArrayMetadata',
  public = list(
    `entries` = NULL,
    initialize = function(
        `entries`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`entries`)) {
        stopifnot(is.vector(`entries`), length(`entries`) != 0)
        sapply(`entries`, function(x) stopifnot(R6::is.R6(x)))
        self$`entries` <- `entries`
      }
    },
    toJSON = function() {
      ArrayMetadataObject <- list()
      if (!is.null(self$`entries`)) {
        ArrayMetadataObject[['entries']] <-
          lapply(self$`entries`, function(x) x$toJSON())
      }

      ArrayMetadataObject
    },
    fromJSON = function(ArrayMetadataJson) {
      ArrayMetadataObject <- jsonlite::fromJSON(ArrayMetadataJson)
      if (!is.null(ArrayMetadataObject$`entries`)) {
        self$`entries` <- ApiClient$new()$deserializeObj(ArrayMetadataObject$`entries`, "array[ArrayMetadataEntry]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entries`)) {
        sprintf(
        '"entries":
        [%s]
',
        paste(sapply(self$`entries`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayMetadataJson) {
      ArrayMetadataObject <- jsonlite::fromJSON(ArrayMetadataJson)
      self$`entries` <- ApiClient$new()$deserializeObj(ArrayMetadataObject$`entries`, "array[ArrayMetadataEntry]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

