# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayTaskBrowserSidebar
#'
#' @description ArrayTaskBrowserSidebar Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field organizations  list( character ) [optional]
#'
#' @field result_count_for_all  integer [optional]
#'
#' @field result_count_by_namespace  object [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayTaskBrowserSidebar <- R6::R6Class(
  'ArrayTaskBrowserSidebar',
  public = list(
    `organizations` = NULL,
    `result_count_for_all` = NULL,
    `result_count_by_namespace` = NULL,
    initialize = function(
        `organizations`=NULL, `result_count_for_all`=NULL, `result_count_by_namespace`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`organizations`)) {
        stopifnot(is.vector(`organizations`), length(`organizations`) != 0)
        sapply(`organizations`, function(x) stopifnot(is.character(x)))
        self$`organizations` <- `organizations`
      }
      if (!is.null(`result_count_for_all`)) {
        stopifnot(is.numeric(`result_count_for_all`), length(`result_count_for_all`) == 1)
        self$`result_count_for_all` <- `result_count_for_all`
      }
      if (!is.null(`result_count_by_namespace`)) {
        self$`result_count_by_namespace` <- `result_count_by_namespace`
      }
    },
    toJSON = function() {
      ArrayTaskBrowserSidebarObject <- list()
      if (!is.null(self$`organizations`)) {
        ArrayTaskBrowserSidebarObject[['organizations']] <-
          self$`organizations`
      }
      if (!is.null(self$`result_count_for_all`)) {
        ArrayTaskBrowserSidebarObject[['result_count_for_all']] <-
          self$`result_count_for_all`
      }
      if (!is.null(self$`result_count_by_namespace`)) {
        ArrayTaskBrowserSidebarObject[['result_count_by_namespace']] <-
          self$`result_count_by_namespace`
      }

      ArrayTaskBrowserSidebarObject
    },
    fromJSON = function(ArrayTaskBrowserSidebarJson) {
      ArrayTaskBrowserSidebarObject <- jsonlite::fromJSON(ArrayTaskBrowserSidebarJson)
      if (!is.null(ArrayTaskBrowserSidebarObject$`organizations`)) {
        self$`organizations` <- ApiClient$new()$deserializeObj(ArrayTaskBrowserSidebarObject$`organizations`, "array[character]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(ArrayTaskBrowserSidebarObject$`result_count_for_all`)) {
        self$`result_count_for_all` <- ArrayTaskBrowserSidebarObject$`result_count_for_all`
      }
      if (!is.null(ArrayTaskBrowserSidebarObject$`result_count_by_namespace`)) {
        self$`result_count_by_namespace` <- ArrayTaskBrowserSidebarObject$`result_count_by_namespace`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`organizations`)) {
        sprintf(
        '"organizations":
           [%s]
        ',
        paste(unlist(lapply(self$`organizations`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`result_count_for_all`)) {
        sprintf(
        '"result_count_for_all":
          %d
                ',
        self$`result_count_for_all`
        )},
        if (!is.null(self$`result_count_by_namespace`)) {
        sprintf(
        '"result_count_by_namespace":
          "%s"
                ',
        self$`result_count_by_namespace`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayTaskBrowserSidebarJson) {
      ArrayTaskBrowserSidebarObject <- jsonlite::fromJSON(ArrayTaskBrowserSidebarJson)
      self$`organizations` <- ApiClient$new()$deserializeObj(ArrayTaskBrowserSidebarObject$`organizations`, "array[character]", loadNamespace("tiledbcloud"))
      self$`result_count_for_all` <- ArrayTaskBrowserSidebarObject$`result_count_for_all`
      self$`result_count_by_namespace` <- ArrayTaskBrowserSidebarObject$`result_count_by_namespace`
      self
    }
  )
)

