# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AWSAccessCredentials
#'
#' @description AWSAccessCredentials Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field secret_access_key  character [optional]
#'
#' @field access_key_id  character [optional]
#'
#' @field service_role_arn  character [optional]
#'
#' @field name  character [optional]
#'
#' @field default  character [optional]
#'
#' @field buckets  list( character ) [optional]
#'
#' @field created_at  character [optional]
#'
#' @field updated_at  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AWSAccessCredentials <- R6::R6Class(
  'AWSAccessCredentials',
  public = list(
    `secret_access_key` = NULL,
    `access_key_id` = NULL,
    `service_role_arn` = NULL,
    `name` = NULL,
    `default` = NULL,
    `buckets` = NULL,
    `created_at` = NULL,
    `updated_at` = NULL,
    initialize = function(
        `secret_access_key`=NULL, `access_key_id`=NULL, `service_role_arn`=NULL, `name`=NULL, `default`=NULL, `buckets`=NULL, `created_at`=NULL, `updated_at`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`secret_access_key`)) {
        stopifnot(is.character(`secret_access_key`), length(`secret_access_key`) == 1)
        self$`secret_access_key` <- `secret_access_key`
      }
      if (!is.null(`access_key_id`)) {
        stopifnot(is.character(`access_key_id`), length(`access_key_id`) == 1)
        self$`access_key_id` <- `access_key_id`
      }
      if (!is.null(`service_role_arn`)) {
        stopifnot(is.character(`service_role_arn`), length(`service_role_arn`) == 1)
        self$`service_role_arn` <- `service_role_arn`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`default`)) {
        self$`default` <- `default`
      }
      if (!is.null(`buckets`)) {
        stopifnot(is.vector(`buckets`), length(`buckets`) != 0)
        sapply(`buckets`, function(x) stopifnot(is.character(x)))
        self$`buckets` <- `buckets`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`updated_at`)) {
        stopifnot(is.character(`updated_at`), length(`updated_at`) == 1)
        self$`updated_at` <- `updated_at`
      }
    },
    toJSON = function() {
      AWSAccessCredentialsObject <- list()
      if (!is.null(self$`secret_access_key`)) {
        AWSAccessCredentialsObject[['secret_access_key']] <-
          self$`secret_access_key`
      }
      if (!is.null(self$`access_key_id`)) {
        AWSAccessCredentialsObject[['access_key_id']] <-
          self$`access_key_id`
      }
      if (!is.null(self$`service_role_arn`)) {
        AWSAccessCredentialsObject[['service_role_arn']] <-
          self$`service_role_arn`
      }
      if (!is.null(self$`name`)) {
        AWSAccessCredentialsObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`default`)) {
        AWSAccessCredentialsObject[['default']] <-
          self$`default`
      }
      if (!is.null(self$`buckets`)) {
        AWSAccessCredentialsObject[['buckets']] <-
          self$`buckets`
      }
      if (!is.null(self$`created_at`)) {
        AWSAccessCredentialsObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`updated_at`)) {
        AWSAccessCredentialsObject[['updated_at']] <-
          self$`updated_at`
      }

      AWSAccessCredentialsObject
    },
    fromJSON = function(AWSAccessCredentialsJson) {
      AWSAccessCredentialsObject <- jsonlite::fromJSON(AWSAccessCredentialsJson)
      if (!is.null(AWSAccessCredentialsObject$`secret_access_key`)) {
        self$`secret_access_key` <- AWSAccessCredentialsObject$`secret_access_key`
      }
      if (!is.null(AWSAccessCredentialsObject$`access_key_id`)) {
        self$`access_key_id` <- AWSAccessCredentialsObject$`access_key_id`
      }
      if (!is.null(AWSAccessCredentialsObject$`service_role_arn`)) {
        self$`service_role_arn` <- AWSAccessCredentialsObject$`service_role_arn`
      }
      if (!is.null(AWSAccessCredentialsObject$`name`)) {
        self$`name` <- AWSAccessCredentialsObject$`name`
      }
      if (!is.null(AWSAccessCredentialsObject$`default`)) {
        self$`default` <- AWSAccessCredentialsObject$`default`
      }
      if (!is.null(AWSAccessCredentialsObject$`buckets`)) {
        self$`buckets` <- ApiClient$new()$deserializeObj(AWSAccessCredentialsObject$`buckets`, "array[character]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(AWSAccessCredentialsObject$`created_at`)) {
        self$`created_at` <- AWSAccessCredentialsObject$`created_at`
      }
      if (!is.null(AWSAccessCredentialsObject$`updated_at`)) {
        self$`updated_at` <- AWSAccessCredentialsObject$`updated_at`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`secret_access_key`)) {
        sprintf(
        '"secret_access_key":
          "%s"
                ',
        self$`secret_access_key`
        )},
        if (!is.null(self$`access_key_id`)) {
        sprintf(
        '"access_key_id":
          "%s"
                ',
        self$`access_key_id`
        )},
        if (!is.null(self$`service_role_arn`)) {
        sprintf(
        '"service_role_arn":
          "%s"
                ',
        self$`service_role_arn`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`default`)) {
        sprintf(
        '"default":
          "%s"
                ',
        self$`default`
        )},
        if (!is.null(self$`buckets`)) {
        sprintf(
        '"buckets":
           [%s]
        ',
        paste(unlist(lapply(self$`buckets`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`updated_at`)) {
        sprintf(
        '"updated_at":
          "%s"
                ',
        self$`updated_at`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AWSAccessCredentialsJson) {
      AWSAccessCredentialsObject <- jsonlite::fromJSON(AWSAccessCredentialsJson)
      self$`secret_access_key` <- AWSAccessCredentialsObject$`secret_access_key`
      self$`access_key_id` <- AWSAccessCredentialsObject$`access_key_id`
      self$`service_role_arn` <- AWSAccessCredentialsObject$`service_role_arn`
      self$`name` <- AWSAccessCredentialsObject$`name`
      self$`default` <- AWSAccessCredentialsObject$`default`
      self$`buckets` <- ApiClient$new()$deserializeObj(AWSAccessCredentialsObject$`buckets`, "array[character]", loadNamespace("tiledbcloud"))
      self$`created_at` <- AWSAccessCredentialsObject$`created_at`
      self$`updated_at` <- AWSAccessCredentialsObject$`updated_at`
      self
    }
  )
)

