# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DimensionCoordinate
#'
#' @description DimensionCoordinate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field int8  integer [optional]
#'
#' @field uint8  integer [optional]
#'
#' @field int16  integer [optional]
#'
#' @field uint16  integer [optional]
#'
#' @field int32  integer [optional]
#'
#' @field uint32  integer [optional]
#'
#' @field int64  integer [optional]
#'
#' @field uint64  integer [optional]
#'
#' @field float32  numeric [optional]
#'
#' @field float64  numeric [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DimensionCoordinate <- R6::R6Class(
  'DimensionCoordinate',
  public = list(
    `int8` = NULL,
    `uint8` = NULL,
    `int16` = NULL,
    `uint16` = NULL,
    `int32` = NULL,
    `uint32` = NULL,
    `int64` = NULL,
    `uint64` = NULL,
    `float32` = NULL,
    `float64` = NULL,
    initialize = function(
        `int8`=NULL, `uint8`=NULL, `int16`=NULL, `uint16`=NULL, `int32`=NULL, `uint32`=NULL, `int64`=NULL, `uint64`=NULL, `float32`=NULL, `float64`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`int8`)) {
        stopifnot(is.numeric(`int8`), length(`int8`) == 1)
        self$`int8` <- `int8`
      }
      if (!is.null(`uint8`)) {
        stopifnot(is.numeric(`uint8`), length(`uint8`) == 1)
        self$`uint8` <- `uint8`
      }
      if (!is.null(`int16`)) {
        stopifnot(is.numeric(`int16`), length(`int16`) == 1)
        self$`int16` <- `int16`
      }
      if (!is.null(`uint16`)) {
        stopifnot(is.numeric(`uint16`), length(`uint16`) == 1)
        self$`uint16` <- `uint16`
      }
      if (!is.null(`int32`)) {
        stopifnot(is.numeric(`int32`), length(`int32`) == 1)
        self$`int32` <- `int32`
      }
      if (!is.null(`uint32`)) {
        stopifnot(is.numeric(`uint32`), length(`uint32`) == 1)
        self$`uint32` <- `uint32`
      }
      if (!is.null(`int64`)) {
        stopifnot(is.numeric(`int64`), length(`int64`) == 1)
        self$`int64` <- `int64`
      }
      if (!is.null(`uint64`)) {
        stopifnot(is.numeric(`uint64`), length(`uint64`) == 1)
        self$`uint64` <- `uint64`
      }
      if (!is.null(`float32`)) {
        stopifnot(is.numeric(`float32`), length(`float32`) == 1)
        self$`float32` <- `float32`
      }
      if (!is.null(`float64`)) {
        stopifnot(is.numeric(`float64`), length(`float64`) == 1)
        self$`float64` <- `float64`
      }
    },
    toJSON = function() {
      DimensionCoordinateObject <- list()
      if (!is.null(self$`int8`)) {
        DimensionCoordinateObject[['int8']] <-
          self$`int8`
      }
      if (!is.null(self$`uint8`)) {
        DimensionCoordinateObject[['uint8']] <-
          self$`uint8`
      }
      if (!is.null(self$`int16`)) {
        DimensionCoordinateObject[['int16']] <-
          self$`int16`
      }
      if (!is.null(self$`uint16`)) {
        DimensionCoordinateObject[['uint16']] <-
          self$`uint16`
      }
      if (!is.null(self$`int32`)) {
        DimensionCoordinateObject[['int32']] <-
          self$`int32`
      }
      if (!is.null(self$`uint32`)) {
        DimensionCoordinateObject[['uint32']] <-
          self$`uint32`
      }
      if (!is.null(self$`int64`)) {
        DimensionCoordinateObject[['int64']] <-
          self$`int64`
      }
      if (!is.null(self$`uint64`)) {
        DimensionCoordinateObject[['uint64']] <-
          self$`uint64`
      }
      if (!is.null(self$`float32`)) {
        DimensionCoordinateObject[['float32']] <-
          self$`float32`
      }
      if (!is.null(self$`float64`)) {
        DimensionCoordinateObject[['float64']] <-
          self$`float64`
      }

      DimensionCoordinateObject
    },
    fromJSON = function(DimensionCoordinateJson) {
      DimensionCoordinateObject <- jsonlite::fromJSON(DimensionCoordinateJson)
      if (!is.null(DimensionCoordinateObject$`int8`)) {
        self$`int8` <- DimensionCoordinateObject$`int8`
      }
      if (!is.null(DimensionCoordinateObject$`uint8`)) {
        self$`uint8` <- DimensionCoordinateObject$`uint8`
      }
      if (!is.null(DimensionCoordinateObject$`int16`)) {
        self$`int16` <- DimensionCoordinateObject$`int16`
      }
      if (!is.null(DimensionCoordinateObject$`uint16`)) {
        self$`uint16` <- DimensionCoordinateObject$`uint16`
      }
      if (!is.null(DimensionCoordinateObject$`int32`)) {
        self$`int32` <- DimensionCoordinateObject$`int32`
      }
      if (!is.null(DimensionCoordinateObject$`uint32`)) {
        self$`uint32` <- DimensionCoordinateObject$`uint32`
      }
      if (!is.null(DimensionCoordinateObject$`int64`)) {
        self$`int64` <- DimensionCoordinateObject$`int64`
      }
      if (!is.null(DimensionCoordinateObject$`uint64`)) {
        self$`uint64` <- DimensionCoordinateObject$`uint64`
      }
      if (!is.null(DimensionCoordinateObject$`float32`)) {
        self$`float32` <- DimensionCoordinateObject$`float32`
      }
      if (!is.null(DimensionCoordinateObject$`float64`)) {
        self$`float64` <- DimensionCoordinateObject$`float64`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`int8`)) {
        sprintf(
        '"int8":
          %d
                ',
        self$`int8`
        )},
        if (!is.null(self$`uint8`)) {
        sprintf(
        '"uint8":
          %d
                ',
        self$`uint8`
        )},
        if (!is.null(self$`int16`)) {
        sprintf(
        '"int16":
          %d
                ',
        self$`int16`
        )},
        if (!is.null(self$`uint16`)) {
        sprintf(
        '"uint16":
          %d
                ',
        self$`uint16`
        )},
        if (!is.null(self$`int32`)) {
        sprintf(
        '"int32":
          %d
                ',
        self$`int32`
        )},
        if (!is.null(self$`uint32`)) {
        sprintf(
        '"uint32":
          %d
                ',
        self$`uint32`
        )},
        if (!is.null(self$`int64`)) {
        sprintf(
        '"int64":
          %d
                ',
        self$`int64`
        )},
        if (!is.null(self$`uint64`)) {
        sprintf(
        '"uint64":
          %d
                ',
        self$`uint64`
        )},
        if (!is.null(self$`float32`)) {
        sprintf(
        '"float32":
          %d
                ',
        self$`float32`
        )},
        if (!is.null(self$`float64`)) {
        sprintf(
        '"float64":
          %d
                ',
        self$`float64`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DimensionCoordinateJson) {
      DimensionCoordinateObject <- jsonlite::fromJSON(DimensionCoordinateJson)
      self$`int8` <- DimensionCoordinateObject$`int8`
      self$`uint8` <- DimensionCoordinateObject$`uint8`
      self$`int16` <- DimensionCoordinateObject$`int16`
      self$`uint16` <- DimensionCoordinateObject$`uint16`
      self$`int32` <- DimensionCoordinateObject$`int32`
      self$`uint32` <- DimensionCoordinateObject$`uint32`
      self$`int64` <- DimensionCoordinateObject$`int64`
      self$`uint64` <- DimensionCoordinateObject$`uint64`
      self$`float32` <- DimensionCoordinateObject$`float32`
      self$`float64` <- DimensionCoordinateObject$`float64`
      self
    }
  )
)

