# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FileCreate
#'
#' @description FileCreate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field input_uri  character [optional]
#'
#' @field output_uri  character [optional]
#'
#' @field name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileCreate <- R6::R6Class(
  'FileCreate',
  public = list(
    `input_uri` = NULL,
    `output_uri` = NULL,
    `name` = NULL,
    initialize = function(
        `input_uri`=NULL, `output_uri`=NULL, `name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`input_uri`)) {
        stopifnot(is.character(`input_uri`), length(`input_uri`) == 1)
        self$`input_uri` <- `input_uri`
      }
      if (!is.null(`output_uri`)) {
        stopifnot(is.character(`output_uri`), length(`output_uri`) == 1)
        self$`output_uri` <- `output_uri`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      FileCreateObject <- list()
      if (!is.null(self$`input_uri`)) {
        FileCreateObject[['input_uri']] <-
          self$`input_uri`
      }
      if (!is.null(self$`output_uri`)) {
        FileCreateObject[['output_uri']] <-
          self$`output_uri`
      }
      if (!is.null(self$`name`)) {
        FileCreateObject[['name']] <-
          self$`name`
      }

      FileCreateObject
    },
    fromJSON = function(FileCreateJson) {
      FileCreateObject <- jsonlite::fromJSON(FileCreateJson)
      if (!is.null(FileCreateObject$`input_uri`)) {
        self$`input_uri` <- FileCreateObject$`input_uri`
      }
      if (!is.null(FileCreateObject$`output_uri`)) {
        self$`output_uri` <- FileCreateObject$`output_uri`
      }
      if (!is.null(FileCreateObject$`name`)) {
        self$`name` <- FileCreateObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`input_uri`)) {
        sprintf(
        '"input_uri":
          "%s"
                ',
        self$`input_uri`
        )},
        if (!is.null(self$`output_uri`)) {
        sprintf(
        '"output_uri":
          "%s"
                ',
        self$`output_uri`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FileCreateJson) {
      FileCreateObject <- jsonlite::fromJSON(FileCreateJson)
      self$`input_uri` <- FileCreateObject$`input_uri`
      self$`output_uri` <- FileCreateObject$`output_uri`
      self$`name` <- FileCreateObject$`name`
      self
    }
  )
)

