# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FileExported
#'
#' @description FileExported Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field output_uri  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileExported <- R6::R6Class(
  'FileExported',
  public = list(
    `output_uri` = NULL,
    initialize = function(
        `output_uri`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`output_uri`)) {
        stopifnot(is.character(`output_uri`), length(`output_uri`) == 1)
        self$`output_uri` <- `output_uri`
      }
    },
    toJSON = function() {
      FileExportedObject <- list()
      if (!is.null(self$`output_uri`)) {
        FileExportedObject[['output_uri']] <-
          self$`output_uri`
      }

      FileExportedObject
    },
    fromJSON = function(FileExportedJson) {
      FileExportedObject <- jsonlite::fromJSON(FileExportedJson)
      if (!is.null(FileExportedObject$`output_uri`)) {
        self$`output_uri` <- FileExportedObject$`output_uri`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`output_uri`)) {
        sprintf(
        '"output_uri":
          "%s"
                ',
        self$`output_uri`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FileExportedJson) {
      FileExportedObject <- jsonlite::fromJSON(FileExportedJson)
      self$`output_uri` <- FileExportedObject$`output_uri`
      self
    }
  )
)

