# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FilterOption
#'
#' @description FilterOption Class
#'
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FilterOption <- R6::R6Class(
    "FilterOption",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)
            enumvec <- .parse_FilterOption()

            stopifnot(length(val) == 1L)

            if (!val %in% enumvec)
                stop("Use one of the valid values: ",
                    paste0(enumvec, collapse = ", "))
            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(FilterOptionJson) {
            private$value <- jsonlite::fromJSON(FilterOptionJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(FilterOptionJson) {
            private$value <- jsonlite::fromJSON(FilterOptionJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_FilterOption <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[COMPRESSION_LEVEL, BIT_WIDTH_MAX_WINDOW, POSITIVE_DELTA_MAX_WINDOW]"
    )
    unlist(strsplit(res, ", "))
}


