# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GenericUDF
#'
#' @description GenericUDF Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field udf_info_name  character [optional]
#'
#' @field language  \link{UDFLanguage} [optional]
#'
#' @field version  character [optional]
#'
#' @field image_name  character [optional]
#'
#' @field exec  character [optional]
#'
#' @field exec_raw  character [optional]
#'
#' @field argument  character [optional]
#'
#' @field result_format  \link{UDFResultType} [optional]
#'
#' @field task_name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GenericUDF <- R6::R6Class(
  'GenericUDF',
  public = list(
    `udf_info_name` = NULL,
    `language` = NULL,
    `version` = NULL,
    `image_name` = NULL,
    `exec` = NULL,
    `exec_raw` = NULL,
    `argument` = NULL,
    `result_format` = NULL,
    `task_name` = NULL,
    initialize = function(
        `udf_info_name`=NULL, `language`=NULL, `version`=NULL, `image_name`=NULL, `exec`=NULL, `exec_raw`=NULL, `argument`=NULL, `result_format`=NULL, `task_name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`udf_info_name`)) {
        stopifnot(is.character(`udf_info_name`), length(`udf_info_name`) == 1)
        self$`udf_info_name` <- `udf_info_name`
      }
      if (!is.null(`language`)) {
        stopifnot(R6::is.R6(`language`))
        self$`language` <- `language`
      }
      if (!is.null(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`image_name`)) {
        stopifnot(is.character(`image_name`), length(`image_name`) == 1)
        self$`image_name` <- `image_name`
      }
      if (!is.null(`exec`)) {
        stopifnot(is.character(`exec`), length(`exec`) == 1)
        self$`exec` <- `exec`
      }
      if (!is.null(`exec_raw`)) {
        stopifnot(is.character(`exec_raw`), length(`exec_raw`) == 1)
        self$`exec_raw` <- `exec_raw`
      }
      if (!is.null(`argument`)) {
        stopifnot(is.character(`argument`), length(`argument`) == 1)
        self$`argument` <- `argument`
      }
      if (!is.null(`result_format`)) {
        stopifnot(R6::is.R6(`result_format`))
        self$`result_format` <- `result_format`
      }
      if (!is.null(`task_name`)) {
        stopifnot(is.character(`task_name`), length(`task_name`) == 1)
        self$`task_name` <- `task_name`
      }
    },
    toJSON = function() {
      GenericUDFObject <- list()
      if (!is.null(self$`udf_info_name`)) {
        GenericUDFObject[['udf_info_name']] <-
          self$`udf_info_name`
      }
      if (!is.null(self$`language`)) {
        GenericUDFObject[['language']] <-
          self$`language`$toJSON()
      }
      if (!is.null(self$`version`)) {
        GenericUDFObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`image_name`)) {
        GenericUDFObject[['image_name']] <-
          self$`image_name`
      }
      if (!is.null(self$`exec`)) {
        GenericUDFObject[['exec']] <-
          self$`exec`
      }
      if (!is.null(self$`exec_raw`)) {
        GenericUDFObject[['exec_raw']] <-
          self$`exec_raw`
      }
      if (!is.null(self$`argument`)) {
        GenericUDFObject[['argument']] <-
          self$`argument`
      }
      if (!is.null(self$`result_format`)) {
        GenericUDFObject[['result_format']] <-
          self$`result_format`$toJSON()
      }
      if (!is.null(self$`task_name`)) {
        GenericUDFObject[['task_name']] <-
          self$`task_name`
      }

      GenericUDFObject
    },
    fromJSON = function(GenericUDFJson) {
      GenericUDFObject <- jsonlite::fromJSON(GenericUDFJson)
      if (!is.null(GenericUDFObject$`udf_info_name`)) {
        self$`udf_info_name` <- GenericUDFObject$`udf_info_name`
      }
      if (!is.null(GenericUDFObject$`language`)) {
        languageObject <- UDFLanguage$new()
        languageObject$fromJSON(jsonlite::toJSON(GenericUDFObject$language, auto_unbox = TRUE, digits = NA))
        self$`language` <- languageObject
      }
      if (!is.null(GenericUDFObject$`version`)) {
        self$`version` <- GenericUDFObject$`version`
      }
      if (!is.null(GenericUDFObject$`image_name`)) {
        self$`image_name` <- GenericUDFObject$`image_name`
      }
      if (!is.null(GenericUDFObject$`exec`)) {
        self$`exec` <- GenericUDFObject$`exec`
      }
      if (!is.null(GenericUDFObject$`exec_raw`)) {
        self$`exec_raw` <- GenericUDFObject$`exec_raw`
      }
      if (!is.null(GenericUDFObject$`argument`)) {
        self$`argument` <- GenericUDFObject$`argument`
      }
      if (!is.null(GenericUDFObject$`result_format`)) {
        result_formatObject <- UDFResultType$new()
        result_formatObject$fromJSON(jsonlite::toJSON(GenericUDFObject$result_format, auto_unbox = TRUE, digits = NA))
        self$`result_format` <- result_formatObject
      }
      if (!is.null(GenericUDFObject$`task_name`)) {
        self$`task_name` <- GenericUDFObject$`task_name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`udf_info_name`)) {
        sprintf(
        '"udf_info_name":
          "%s"
                ',
        self$`udf_info_name`
        )},
        if (!is.null(self$`language`)) {
        sprintf(
        '"language":
        %s
        ',
        jsonlite::toJSON(self$`language`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          "%s"
                ',
        self$`version`
        )},
        if (!is.null(self$`image_name`)) {
        sprintf(
        '"image_name":
          "%s"
                ',
        self$`image_name`
        )},
        if (!is.null(self$`exec`)) {
        sprintf(
        '"exec":
          "%s"
                ',
        self$`exec`
        )},
        if (!is.null(self$`exec_raw`)) {
        sprintf(
        '"exec_raw":
          "%s"
                ',
        self$`exec_raw`
        )},
        if (!is.null(self$`argument`)) {
        sprintf(
        '"argument":
          "%s"
                ',
        self$`argument`
        )},
        if (!is.null(self$`result_format`)) {
        sprintf(
        '"result_format":
        %s
        ',
        jsonlite::toJSON(self$`result_format`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`task_name`)) {
        sprintf(
        '"task_name":
          "%s"
                ',
        self$`task_name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GenericUDFJson) {
      GenericUDFObject <- jsonlite::fromJSON(GenericUDFJson)
      self$`udf_info_name` <- GenericUDFObject$`udf_info_name`
      self$`language` <- UDFLanguage$new()$fromJSON(jsonlite::toJSON(GenericUDFObject$language, auto_unbox = TRUE, digits = NA))
      self$`version` <- GenericUDFObject$`version`
      self$`image_name` <- GenericUDFObject$`image_name`
      self$`exec` <- GenericUDFObject$`exec`
      self$`exec_raw` <- GenericUDFObject$`exec_raw`
      self$`argument` <- GenericUDFObject$`argument`
      self$`result_format` <- UDFResultType$new()$fromJSON(jsonlite::toJSON(GenericUDFObject$result_format, auto_unbox = TRUE, digits = NA))
      self$`task_name` <- GenericUDFObject$`task_name`
      self
    }
  )
)

