# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupMember
#'
#' @description GroupMember Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field namespace  character [optional]
#'
#' @field name  character [optional]
#'
#' @field member_type  \link{GroupMemberType} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupMember <- R6::R6Class(
  'GroupMember',
  public = list(
    `namespace` = NULL,
    `name` = NULL,
    `member_type` = NULL,
    initialize = function(
        `namespace`=NULL, `name`=NULL, `member_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`member_type`)) {
        stopifnot(R6::is.R6(`member_type`))
        self$`member_type` <- `member_type`
      }
    },
    toJSON = function() {
      GroupMemberObject <- list()
      if (!is.null(self$`namespace`)) {
        GroupMemberObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        GroupMemberObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`member_type`)) {
        GroupMemberObject[['member_type']] <-
          self$`member_type`$toJSON()
      }

      GroupMemberObject
    },
    fromJSON = function(GroupMemberJson) {
      GroupMemberObject <- jsonlite::fromJSON(GroupMemberJson)
      if (!is.null(GroupMemberObject$`namespace`)) {
        self$`namespace` <- GroupMemberObject$`namespace`
      }
      if (!is.null(GroupMemberObject$`name`)) {
        self$`name` <- GroupMemberObject$`name`
      }
      if (!is.null(GroupMemberObject$`member_type`)) {
        member_typeObject <- GroupMemberType$new()
        member_typeObject$fromJSON(jsonlite::toJSON(GroupMemberObject$member_type, auto_unbox = TRUE, digits = NA))
        self$`member_type` <- member_typeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`member_type`)) {
        sprintf(
        '"member_type":
        %s
        ',
        jsonlite::toJSON(self$`member_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupMemberJson) {
      GroupMemberObject <- jsonlite::fromJSON(GroupMemberJson)
      self$`namespace` <- GroupMemberObject$`namespace`
      self$`name` <- GroupMemberObject$`name`
      self$`member_type` <- GroupMemberType$new()$fromJSON(jsonlite::toJSON(GroupMemberObject$member_type, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

