# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Group
#'
#' @description Group Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field namespace  character [optional]
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Group <- R6::R6Class(
  'Group',
  public = list(
    `id` = NULL,
    `namespace` = NULL,
    `name` = NULL,
    `description` = NULL,
    initialize = function(
        `id`=NULL, `namespace`=NULL, `name`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      GroupObject <- list()
      if (!is.null(self$`id`)) {
        GroupObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`namespace`)) {
        GroupObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        GroupObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        GroupObject[['description']] <-
          self$`description`
      }

      GroupObject
    },
    fromJSON = function(GroupJson) {
      GroupObject <- jsonlite::fromJSON(GroupJson)
      if (!is.null(GroupObject$`id`)) {
        self$`id` <- GroupObject$`id`
      }
      if (!is.null(GroupObject$`namespace`)) {
        self$`namespace` <- GroupObject$`namespace`
      }
      if (!is.null(GroupObject$`name`)) {
        self$`name` <- GroupObject$`name`
      }
      if (!is.null(GroupObject$`description`)) {
        self$`description` <- GroupObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupJson) {
      GroupObject <- jsonlite::fromJSON(GroupJson)
      self$`id` <- GroupObject$`id`
      self$`namespace` <- GroupObject$`namespace`
      self$`name` <- GroupObject$`name`
      self$`description` <- GroupObject$`description`
      self
    }
  )
)

