# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupContentsFilterData
#'
#' @description GroupContentsFilterData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field namespaces  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupContentsFilterData <- R6::R6Class(
  'GroupContentsFilterData',
  public = list(
    `namespaces` = NULL,
    initialize = function(
        `namespaces`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`namespaces`)) {
        stopifnot(is.vector(`namespaces`), length(`namespaces`) != 0)
        sapply(`namespaces`, function(x) stopifnot(is.character(x)))
        self$`namespaces` <- `namespaces`
      }
    },
    toJSON = function() {
      GroupContentsFilterDataObject <- list()
      if (!is.null(self$`namespaces`)) {
        GroupContentsFilterDataObject[['namespaces']] <-
          self$`namespaces`
      }

      GroupContentsFilterDataObject
    },
    fromJSON = function(GroupContentsFilterDataJson) {
      GroupContentsFilterDataObject <- jsonlite::fromJSON(GroupContentsFilterDataJson)
      if (!is.null(GroupContentsFilterDataObject$`namespaces`)) {
        self$`namespaces` <- ApiClient$new()$deserializeObj(GroupContentsFilterDataObject$`namespaces`, "array[character]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`namespaces`)) {
        sprintf(
        '"namespaces":
           [%s]
        ',
        paste(unlist(lapply(self$`namespaces`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupContentsFilterDataJson) {
      GroupContentsFilterDataObject <- jsonlite::fromJSON(GroupContentsFilterDataJson)
      self$`namespaces` <- ApiClient$new()$deserializeObj(GroupContentsFilterDataObject$`namespaces`, "array[character]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

