# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupListing
#'
#' @description GroupListing Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field namespace  character [optional]
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @field groups  list( \link{Group} ) [optional]
#'
#' @field assets  list( \link{ArrayInfo} ) [optional]
#'
#' @field pagination_metadata  \link{PaginationMetadata} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupListing <- R6::R6Class(
  'GroupListing',
  public = list(
    `id` = NULL,
    `namespace` = NULL,
    `name` = NULL,
    `description` = NULL,
    `groups` = NULL,
    `assets` = NULL,
    `pagination_metadata` = NULL,
    initialize = function(
        `id`=NULL, `namespace`=NULL, `name`=NULL, `description`=NULL, `groups`=NULL, `assets`=NULL, `pagination_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`groups`)) {
        stopifnot(is.vector(`groups`), length(`groups`) != 0)
        sapply(`groups`, function(x) stopifnot(R6::is.R6(x)))
        self$`groups` <- `groups`
      }
      if (!is.null(`assets`)) {
        stopifnot(is.vector(`assets`), length(`assets`) != 0)
        sapply(`assets`, function(x) stopifnot(R6::is.R6(x)))
        self$`assets` <- `assets`
      }
      if (!is.null(`pagination_metadata`)) {
        stopifnot(R6::is.R6(`pagination_metadata`))
        self$`pagination_metadata` <- `pagination_metadata`
      }
    },
    toJSON = function() {
      GroupListingObject <- list()
      if (!is.null(self$`id`)) {
        GroupListingObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`namespace`)) {
        GroupListingObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        GroupListingObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        GroupListingObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`groups`)) {
        GroupListingObject[['groups']] <-
          lapply(self$`groups`, function(x) x$toJSON())
      }
      if (!is.null(self$`assets`)) {
        GroupListingObject[['assets']] <-
          lapply(self$`assets`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination_metadata`)) {
        GroupListingObject[['pagination_metadata']] <-
          self$`pagination_metadata`$toJSON()
      }

      GroupListingObject
    },
    fromJSON = function(GroupListingJson) {
      GroupListingObject <- jsonlite::fromJSON(GroupListingJson)
      if (!is.null(GroupListingObject$`id`)) {
        self$`id` <- GroupListingObject$`id`
      }
      if (!is.null(GroupListingObject$`namespace`)) {
        self$`namespace` <- GroupListingObject$`namespace`
      }
      if (!is.null(GroupListingObject$`name`)) {
        self$`name` <- GroupListingObject$`name`
      }
      if (!is.null(GroupListingObject$`description`)) {
        self$`description` <- GroupListingObject$`description`
      }
      if (!is.null(GroupListingObject$`groups`)) {
        self$`groups` <- ApiClient$new()$deserializeObj(GroupListingObject$`groups`, "array[Group]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupListingObject$`assets`)) {
        self$`assets` <- ApiClient$new()$deserializeObj(GroupListingObject$`assets`, "array[ArrayInfo]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupListingObject$`pagination_metadata`)) {
        pagination_metadataObject <- PaginationMetadata$new()
        pagination_metadataObject$fromJSON(jsonlite::toJSON(GroupListingObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
        self$`pagination_metadata` <- pagination_metadataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`groups`)) {
        sprintf(
        '"groups":
        [%s]
',
        paste(sapply(self$`groups`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`assets`)) {
        sprintf(
        '"assets":
        [%s]
',
        paste(sapply(self$`assets`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination_metadata`)) {
        sprintf(
        '"pagination_metadata":
        %s
        ',
        jsonlite::toJSON(self$`pagination_metadata`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupListingJson) {
      GroupListingObject <- jsonlite::fromJSON(GroupListingJson)
      self$`id` <- GroupListingObject$`id`
      self$`namespace` <- GroupListingObject$`namespace`
      self$`name` <- GroupListingObject$`name`
      self$`description` <- GroupListingObject$`description`
      self$`groups` <- ApiClient$new()$deserializeObj(GroupListingObject$`groups`, "array[Group]", loadNamespace("tiledbcloud"))
      self$`assets` <- ApiClient$new()$deserializeObj(GroupListingObject$`assets`, "array[ArrayInfo]", loadNamespace("tiledbcloud"))
      self$`pagination_metadata` <- PaginationMetadata$new()$fromJSON(jsonlite::toJSON(GroupListingObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

