# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupChanges
#'
#' @description GroupChanges Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field add  list( \link{GroupMember} ) [optional]
#'
#' @field remove  list( \link{GroupMember} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupChanges <- R6::R6Class(
  'GroupChanges',
  public = list(
    `add` = NULL,
    `remove` = NULL,
    initialize = function(
        `add`=NULL, `remove`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`add`)) {
        stopifnot(is.vector(`add`), length(`add`) != 0)
        sapply(`add`, function(x) stopifnot(R6::is.R6(x)))
        self$`add` <- `add`
      }
      if (!is.null(`remove`)) {
        stopifnot(is.vector(`remove`), length(`remove`) != 0)
        sapply(`remove`, function(x) stopifnot(R6::is.R6(x)))
        self$`remove` <- `remove`
      }
    },
    toJSON = function() {
      GroupChangesObject <- list()
      if (!is.null(self$`add`)) {
        GroupChangesObject[['add']] <-
          lapply(self$`add`, function(x) x$toJSON())
      }
      if (!is.null(self$`remove`)) {
        GroupChangesObject[['remove']] <-
          lapply(self$`remove`, function(x) x$toJSON())
      }

      GroupChangesObject
    },
    fromJSON = function(GroupChangesJson) {
      GroupChangesObject <- jsonlite::fromJSON(GroupChangesJson)
      if (!is.null(GroupChangesObject$`add`)) {
        self$`add` <- ApiClient$new()$deserializeObj(GroupChangesObject$`add`, "array[GroupMember]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupChangesObject$`remove`)) {
        self$`remove` <- ApiClient$new()$deserializeObj(GroupChangesObject$`remove`, "array[GroupMember]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`add`)) {
        sprintf(
        '"add":
        [%s]
',
        paste(sapply(self$`add`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`remove`)) {
        sprintf(
        '"remove":
        [%s]
',
        paste(sapply(self$`remove`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupChangesJson) {
      GroupChangesObject <- jsonlite::fromJSON(GroupChangesJson)
      self$`add` <- ApiClient$new()$deserializeObj(GroupChangesObject$`add`, "array[GroupMember]", loadNamespace("tiledbcloud"))
      self$`remove` <- ApiClient$new()$deserializeObj(GroupChangesObject$`remove`, "array[GroupMember]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

