# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupContents
#'
#' @description GroupContents Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field entries  list( \link{GroupEntry} ) [optional]
#'
#' @field pagination_metadata  \link{PaginationMetadata} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupContents <- R6::R6Class(
  'GroupContents',
  public = list(
    `entries` = NULL,
    `pagination_metadata` = NULL,
    initialize = function(
        `entries`=NULL, `pagination_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`entries`)) {
        stopifnot(is.vector(`entries`), length(`entries`) != 0)
        sapply(`entries`, function(x) stopifnot(R6::is.R6(x)))
        self$`entries` <- `entries`
      }
      if (!is.null(`pagination_metadata`)) {
        stopifnot(R6::is.R6(`pagination_metadata`))
        self$`pagination_metadata` <- `pagination_metadata`
      }
    },
    toJSON = function() {
      GroupContentsObject <- list()
      if (!is.null(self$`entries`)) {
        GroupContentsObject[['entries']] <-
          lapply(self$`entries`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination_metadata`)) {
        GroupContentsObject[['pagination_metadata']] <-
          self$`pagination_metadata`$toJSON()
      }

      GroupContentsObject
    },
    fromJSON = function(GroupContentsJson) {
      GroupContentsObject <- jsonlite::fromJSON(GroupContentsJson)
      if (!is.null(GroupContentsObject$`entries`)) {
        self$`entries` <- ApiClient$new()$deserializeObj(GroupContentsObject$`entries`, "array[GroupEntry]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupContentsObject$`pagination_metadata`)) {
        pagination_metadataObject <- PaginationMetadata$new()
        pagination_metadataObject$fromJSON(jsonlite::toJSON(GroupContentsObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
        self$`pagination_metadata` <- pagination_metadataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entries`)) {
        sprintf(
        '"entries":
        [%s]
',
        paste(sapply(self$`entries`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination_metadata`)) {
        sprintf(
        '"pagination_metadata":
        %s
        ',
        jsonlite::toJSON(self$`pagination_metadata`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupContentsJson) {
      GroupContentsObject <- jsonlite::fromJSON(GroupContentsJson)
      self$`entries` <- ApiClient$new()$deserializeObj(GroupContentsObject$`entries`, "array[GroupEntry]", loadNamespace("tiledbcloud"))
      self$`pagination_metadata` <- PaginationMetadata$new()$fromJSON(jsonlite::toJSON(GroupContentsObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

