# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupBrowserData
#'
#' @description GroupBrowserData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field groups  list( \link{GroupInfo} ) [optional]
#'
#' @field pagination_metadata  \link{PaginationMetadata} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupBrowserData <- R6::R6Class(
  'GroupBrowserData',
  public = list(
    `groups` = NULL,
    `pagination_metadata` = NULL,
    initialize = function(
        `groups`=NULL, `pagination_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`groups`)) {
        stopifnot(is.vector(`groups`), length(`groups`) != 0)
        sapply(`groups`, function(x) stopifnot(R6::is.R6(x)))
        self$`groups` <- `groups`
      }
      if (!is.null(`pagination_metadata`)) {
        stopifnot(R6::is.R6(`pagination_metadata`))
        self$`pagination_metadata` <- `pagination_metadata`
      }
    },
    toJSON = function() {
      GroupBrowserDataObject <- list()
      if (!is.null(self$`groups`)) {
        GroupBrowserDataObject[['groups']] <-
          lapply(self$`groups`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination_metadata`)) {
        GroupBrowserDataObject[['pagination_metadata']] <-
          self$`pagination_metadata`$toJSON()
      }

      GroupBrowserDataObject
    },
    fromJSON = function(GroupBrowserDataJson) {
      GroupBrowserDataObject <- jsonlite::fromJSON(GroupBrowserDataJson)
      if (!is.null(GroupBrowserDataObject$`groups`)) {
        self$`groups` <- ApiClient$new()$deserializeObj(GroupBrowserDataObject$`groups`, "array[GroupInfo]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupBrowserDataObject$`pagination_metadata`)) {
        pagination_metadataObject <- PaginationMetadata$new()
        pagination_metadataObject$fromJSON(jsonlite::toJSON(GroupBrowserDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
        self$`pagination_metadata` <- pagination_metadataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`groups`)) {
        sprintf(
        '"groups":
        [%s]
',
        paste(sapply(self$`groups`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination_metadata`)) {
        sprintf(
        '"pagination_metadata":
        %s
        ',
        jsonlite::toJSON(self$`pagination_metadata`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupBrowserDataJson) {
      GroupBrowserDataObject <- jsonlite::fromJSON(GroupBrowserDataJson)
      self$`groups` <- ApiClient$new()$deserializeObj(GroupBrowserDataObject$`groups`, "array[GroupInfo]", loadNamespace("tiledbcloud"))
      self$`pagination_metadata` <- PaginationMetadata$new()$fromJSON(jsonlite::toJSON(GroupBrowserDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

