# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupInfo
#'
#' @description GroupInfo Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field namespace  character [optional]
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @field uri  character [optional]
#'
#' @field tiledb_uri  character [optional]
#'
#' @field asset_count  numeric [optional]
#'
#' @field group_count  numeric [optional]
#'
#' @field size  numeric [optional]
#'
#' @field last_accessed  character [optional]
#'
#' @field allowed_actions  list( \link{GroupActions} ) [optional]
#'
#' @field logo  character [optional]
#'
#' @field access_credentials_name  character [optional]
#'
#' @field share_count  numeric [optional]
#'
#' @field public_share  character [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @field license_id  character [optional]
#'
#' @field license_text  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupInfo <- R6::R6Class(
  'GroupInfo',
  public = list(
    `id` = NULL,
    `namespace` = NULL,
    `name` = NULL,
    `description` = NULL,
    `uri` = NULL,
    `tiledb_uri` = NULL,
    `asset_count` = NULL,
    `group_count` = NULL,
    `size` = NULL,
    `last_accessed` = NULL,
    `allowed_actions` = NULL,
    `logo` = NULL,
    `access_credentials_name` = NULL,
    `share_count` = NULL,
    `public_share` = NULL,
    `tags` = NULL,
    `license_id` = NULL,
    `license_text` = NULL,
    initialize = function(
        `id`=NULL, `namespace`=NULL, `name`=NULL, `description`=NULL, `uri`=NULL, `tiledb_uri`=NULL, `asset_count`=NULL, `group_count`=NULL, `size`=NULL, `last_accessed`=NULL, `allowed_actions`=NULL, `logo`=NULL, `access_credentials_name`=NULL, `share_count`=NULL, `public_share`=NULL, `tags`=NULL, `license_id`=NULL, `license_text`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!is.null(`tiledb_uri`)) {
        stopifnot(is.character(`tiledb_uri`), length(`tiledb_uri`) == 1)
        self$`tiledb_uri` <- `tiledb_uri`
      }
      if (!is.null(`asset_count`)) {
        self$`asset_count` <- `asset_count`
      }
      if (!is.null(`group_count`)) {
        self$`group_count` <- `group_count`
      }
      if (!is.null(`size`)) {
        self$`size` <- `size`
      }
      if (!is.null(`last_accessed`)) {
        stopifnot(is.character(`last_accessed`), length(`last_accessed`) == 1)
        self$`last_accessed` <- `last_accessed`
      }
      if (!is.null(`allowed_actions`)) {
        stopifnot(is.vector(`allowed_actions`), length(`allowed_actions`) != 0)
        sapply(`allowed_actions`, function(x) stopifnot(R6::is.R6(x)))
        self$`allowed_actions` <- `allowed_actions`
      }
      if (!is.null(`logo`)) {
        stopifnot(is.character(`logo`), length(`logo`) == 1)
        self$`logo` <- `logo`
      }
      if (!is.null(`access_credentials_name`)) {
        stopifnot(is.character(`access_credentials_name`), length(`access_credentials_name`) == 1)
        self$`access_credentials_name` <- `access_credentials_name`
      }
      if (!is.null(`share_count`)) {
        self$`share_count` <- `share_count`
      }
      if (!is.null(`public_share`)) {
        self$`public_share` <- `public_share`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!is.null(`license_id`)) {
        stopifnot(is.character(`license_id`), length(`license_id`) == 1)
        self$`license_id` <- `license_id`
      }
      if (!is.null(`license_text`)) {
        stopifnot(is.character(`license_text`), length(`license_text`) == 1)
        self$`license_text` <- `license_text`
      }
    },
    toJSON = function() {
      GroupInfoObject <- list()
      if (!is.null(self$`id`)) {
        GroupInfoObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`namespace`)) {
        GroupInfoObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        GroupInfoObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        GroupInfoObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`uri`)) {
        GroupInfoObject[['uri']] <-
          self$`uri`
      }
      if (!is.null(self$`tiledb_uri`)) {
        GroupInfoObject[['tiledb_uri']] <-
          self$`tiledb_uri`
      }
      if (!is.null(self$`asset_count`)) {
        GroupInfoObject[['asset_count']] <-
          self$`asset_count`
      }
      if (!is.null(self$`group_count`)) {
        GroupInfoObject[['group_count']] <-
          self$`group_count`
      }
      if (!is.null(self$`size`)) {
        GroupInfoObject[['size']] <-
          self$`size`
      }
      if (!is.null(self$`last_accessed`)) {
        GroupInfoObject[['last_accessed']] <-
          self$`last_accessed`
      }
      if (!is.null(self$`allowed_actions`)) {
        GroupInfoObject[['allowed_actions']] <-
          lapply(self$`allowed_actions`, function(x) x$toJSON())
      }
      if (!is.null(self$`logo`)) {
        GroupInfoObject[['logo']] <-
          self$`logo`
      }
      if (!is.null(self$`access_credentials_name`)) {
        GroupInfoObject[['access_credentials_name']] <-
          self$`access_credentials_name`
      }
      if (!is.null(self$`share_count`)) {
        GroupInfoObject[['share_count']] <-
          self$`share_count`
      }
      if (!is.null(self$`public_share`)) {
        GroupInfoObject[['public_share']] <-
          self$`public_share`
      }
      if (!is.null(self$`tags`)) {
        GroupInfoObject[['tags']] <-
          self$`tags`
      }
      if (!is.null(self$`license_id`)) {
        GroupInfoObject[['license_id']] <-
          self$`license_id`
      }
      if (!is.null(self$`license_text`)) {
        GroupInfoObject[['license_text']] <-
          self$`license_text`
      }

      GroupInfoObject
    },
    fromJSON = function(GroupInfoJson) {
      GroupInfoObject <- jsonlite::fromJSON(GroupInfoJson)
      if (!is.null(GroupInfoObject$`id`)) {
        self$`id` <- GroupInfoObject$`id`
      }
      if (!is.null(GroupInfoObject$`namespace`)) {
        self$`namespace` <- GroupInfoObject$`namespace`
      }
      if (!is.null(GroupInfoObject$`name`)) {
        self$`name` <- GroupInfoObject$`name`
      }
      if (!is.null(GroupInfoObject$`description`)) {
        self$`description` <- GroupInfoObject$`description`
      }
      if (!is.null(GroupInfoObject$`uri`)) {
        self$`uri` <- GroupInfoObject$`uri`
      }
      if (!is.null(GroupInfoObject$`tiledb_uri`)) {
        self$`tiledb_uri` <- GroupInfoObject$`tiledb_uri`
      }
      if (!is.null(GroupInfoObject$`asset_count`)) {
        self$`asset_count` <- GroupInfoObject$`asset_count`
      }
      if (!is.null(GroupInfoObject$`group_count`)) {
        self$`group_count` <- GroupInfoObject$`group_count`
      }
      if (!is.null(GroupInfoObject$`size`)) {
        self$`size` <- GroupInfoObject$`size`
      }
      if (!is.null(GroupInfoObject$`last_accessed`)) {
        self$`last_accessed` <- GroupInfoObject$`last_accessed`
      }
      if (!is.null(GroupInfoObject$`allowed_actions`)) {
        self$`allowed_actions` <- ApiClient$new()$deserializeObj(GroupInfoObject$`allowed_actions`, "array[GroupActions]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupInfoObject$`logo`)) {
        self$`logo` <- GroupInfoObject$`logo`
      }
      if (!is.null(GroupInfoObject$`access_credentials_name`)) {
        self$`access_credentials_name` <- GroupInfoObject$`access_credentials_name`
      }
      if (!is.null(GroupInfoObject$`share_count`)) {
        self$`share_count` <- GroupInfoObject$`share_count`
      }
      if (!is.null(GroupInfoObject$`public_share`)) {
        self$`public_share` <- GroupInfoObject$`public_share`
      }
      if (!is.null(GroupInfoObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(GroupInfoObject$`tags`, "array[character]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(GroupInfoObject$`license_id`)) {
        self$`license_id` <- GroupInfoObject$`license_id`
      }
      if (!is.null(GroupInfoObject$`license_text`)) {
        self$`license_text` <- GroupInfoObject$`license_text`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`uri`)) {
        sprintf(
        '"uri":
          "%s"
                ',
        self$`uri`
        )},
        if (!is.null(self$`tiledb_uri`)) {
        sprintf(
        '"tiledb_uri":
          "%s"
                ',
        self$`tiledb_uri`
        )},
        if (!is.null(self$`asset_count`)) {
        sprintf(
        '"asset_count":
          %d
                ',
        self$`asset_count`
        )},
        if (!is.null(self$`group_count`)) {
        sprintf(
        '"group_count":
          %d
                ',
        self$`group_count`
        )},
        if (!is.null(self$`size`)) {
        sprintf(
        '"size":
          %d
                ',
        self$`size`
        )},
        if (!is.null(self$`last_accessed`)) {
        sprintf(
        '"last_accessed":
          "%s"
                ',
        self$`last_accessed`
        )},
        if (!is.null(self$`allowed_actions`)) {
        sprintf(
        '"allowed_actions":
        [%s]
',
        paste(sapply(self$`allowed_actions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`logo`)) {
        sprintf(
        '"logo":
          "%s"
                ',
        self$`logo`
        )},
        if (!is.null(self$`access_credentials_name`)) {
        sprintf(
        '"access_credentials_name":
          "%s"
                ',
        self$`access_credentials_name`
        )},
        if (!is.null(self$`share_count`)) {
        sprintf(
        '"share_count":
          %d
                ',
        self$`share_count`
        )},
        if (!is.null(self$`public_share`)) {
        sprintf(
        '"public_share":
          "%s"
                ',
        self$`public_share`
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`license_id`)) {
        sprintf(
        '"license_id":
          "%s"
                ',
        self$`license_id`
        )},
        if (!is.null(self$`license_text`)) {
        sprintf(
        '"license_text":
          "%s"
                ',
        self$`license_text`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupInfoJson) {
      GroupInfoObject <- jsonlite::fromJSON(GroupInfoJson)
      self$`id` <- GroupInfoObject$`id`
      self$`namespace` <- GroupInfoObject$`namespace`
      self$`name` <- GroupInfoObject$`name`
      self$`description` <- GroupInfoObject$`description`
      self$`uri` <- GroupInfoObject$`uri`
      self$`tiledb_uri` <- GroupInfoObject$`tiledb_uri`
      self$`asset_count` <- GroupInfoObject$`asset_count`
      self$`group_count` <- GroupInfoObject$`group_count`
      self$`size` <- GroupInfoObject$`size`
      self$`last_accessed` <- GroupInfoObject$`last_accessed`
      self$`allowed_actions` <- ApiClient$new()$deserializeObj(GroupInfoObject$`allowed_actions`, "array[GroupActions]", loadNamespace("tiledbcloud"))
      self$`logo` <- GroupInfoObject$`logo`
      self$`access_credentials_name` <- GroupInfoObject$`access_credentials_name`
      self$`share_count` <- GroupInfoObject$`share_count`
      self$`public_share` <- GroupInfoObject$`public_share`
      self$`tags` <- ApiClient$new()$deserializeObj(GroupInfoObject$`tags`, "array[character]", loadNamespace("tiledbcloud"))
      self$`license_id` <- GroupInfoObject$`license_id`
      self$`license_text` <- GroupInfoObject$`license_text`
      self
    }
  )
)

