# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvitationData
#'
#' @description InvitationData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field invitations  list( \link{Invitation} ) [optional]
#'
#' @field pagination_metadata  \link{PaginationMetadata} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvitationData <- R6::R6Class(
  'InvitationData',
  public = list(
    `invitations` = NULL,
    `pagination_metadata` = NULL,
    initialize = function(
        `invitations`=NULL, `pagination_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`invitations`)) {
        stopifnot(is.vector(`invitations`), length(`invitations`) != 0)
        sapply(`invitations`, function(x) stopifnot(R6::is.R6(x)))
        self$`invitations` <- `invitations`
      }
      if (!is.null(`pagination_metadata`)) {
        stopifnot(R6::is.R6(`pagination_metadata`))
        self$`pagination_metadata` <- `pagination_metadata`
      }
    },
    toJSON = function() {
      InvitationDataObject <- list()
      if (!is.null(self$`invitations`)) {
        InvitationDataObject[['invitations']] <-
          lapply(self$`invitations`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination_metadata`)) {
        InvitationDataObject[['pagination_metadata']] <-
          self$`pagination_metadata`$toJSON()
      }

      InvitationDataObject
    },
    fromJSON = function(InvitationDataJson) {
      InvitationDataObject <- jsonlite::fromJSON(InvitationDataJson)
      if (!is.null(InvitationDataObject$`invitations`)) {
        self$`invitations` <- ApiClient$new()$deserializeObj(InvitationDataObject$`invitations`, "array[Invitation]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(InvitationDataObject$`pagination_metadata`)) {
        pagination_metadataObject <- PaginationMetadata$new()
        pagination_metadataObject$fromJSON(jsonlite::toJSON(InvitationDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
        self$`pagination_metadata` <- pagination_metadataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`invitations`)) {
        sprintf(
        '"invitations":
        [%s]
',
        paste(sapply(self$`invitations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination_metadata`)) {
        sprintf(
        '"pagination_metadata":
        %s
        ',
        jsonlite::toJSON(self$`pagination_metadata`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvitationDataJson) {
      InvitationDataObject <- jsonlite::fromJSON(InvitationDataJson)
      self$`invitations` <- ApiClient$new()$deserializeObj(InvitationDataObject$`invitations`, "array[Invitation]", loadNamespace("tiledbcloud"))
      self$`pagination_metadata` <- PaginationMetadata$new()$fromJSON(jsonlite::toJSON(InvitationDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

