# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvitationOrganizationJoinEmail
#'
#' @description InvitationOrganizationJoinEmail Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field actions  list( \link{NamespaceActions} ) [optional]
#'
#' @field organization_role  \link{OrganizationRoles} 
#'
#' @field invitee_email  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvitationOrganizationJoinEmail <- R6::R6Class(
  'InvitationOrganizationJoinEmail',
  public = list(
    `actions` = NULL,
    `organization_role` = NULL,
    `invitee_email` = NULL,
    initialize = function(
        `organization_role`, `invitee_email`, `actions`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`organization_role`)) {
        stopifnot(R6::is.R6(`organization_role`))
        self$`organization_role` <- `organization_role`
      }
      if (!missing(`invitee_email`)) {
        stopifnot(is.vector(`invitee_email`), length(`invitee_email`) != 0)
        sapply(`invitee_email`, function(x) stopifnot(is.character(x)))
        self$`invitee_email` <- `invitee_email`
      }
      if (!is.null(`actions`)) {
        stopifnot(is.vector(`actions`), length(`actions`) != 0)
        sapply(`actions`, function(x) stopifnot(R6::is.R6(x)))
        self$`actions` <- `actions`
      }
    },
    toJSON = function() {
      InvitationOrganizationJoinEmailObject <- list()
      if (!is.null(self$`actions`)) {
        InvitationOrganizationJoinEmailObject[['actions']] <-
          lapply(self$`actions`, function(x) x$toJSON())
      }
      if (!is.null(self$`organization_role`)) {
        InvitationOrganizationJoinEmailObject[['organization_role']] <-
          self$`organization_role`$toJSON()
      }
      if (!is.null(self$`invitee_email`)) {
        InvitationOrganizationJoinEmailObject[['invitee_email']] <-
          self$`invitee_email`
      }

      InvitationOrganizationJoinEmailObject
    },
    fromJSON = function(InvitationOrganizationJoinEmailJson) {
      InvitationOrganizationJoinEmailObject <- jsonlite::fromJSON(InvitationOrganizationJoinEmailJson)
      if (!is.null(InvitationOrganizationJoinEmailObject$`actions`)) {
        self$`actions` <- ApiClient$new()$deserializeObj(InvitationOrganizationJoinEmailObject$`actions`, "array[NamespaceActions]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(InvitationOrganizationJoinEmailObject$`organization_role`)) {
        organization_roleObject <- OrganizationRoles$new()
        organization_roleObject$fromJSON(jsonlite::toJSON(InvitationOrganizationJoinEmailObject$organization_role, auto_unbox = TRUE, digits = NA))
        self$`organization_role` <- organization_roleObject
      }
      if (!is.null(InvitationOrganizationJoinEmailObject$`invitee_email`)) {
        self$`invitee_email` <- ApiClient$new()$deserializeObj(InvitationOrganizationJoinEmailObject$`invitee_email`, "array[character]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`actions`)) {
        sprintf(
        '"actions":
        [%s]
',
        paste(sapply(self$`actions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`organization_role`)) {
        sprintf(
        '"organization_role":
        %s
        ',
        jsonlite::toJSON(self$`organization_role`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`invitee_email`)) {
        sprintf(
        '"invitee_email":
           [%s]
        ',
        paste(unlist(lapply(self$`invitee_email`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvitationOrganizationJoinEmailJson) {
      InvitationOrganizationJoinEmailObject <- jsonlite::fromJSON(InvitationOrganizationJoinEmailJson)
      self$`actions` <- ApiClient$new()$deserializeObj(InvitationOrganizationJoinEmailObject$`actions`, "array[NamespaceActions]", loadNamespace("tiledbcloud"))
      self$`organization_role` <- OrganizationRoles$new()$fromJSON(jsonlite::toJSON(InvitationOrganizationJoinEmailObject$organization_role, auto_unbox = TRUE, digits = NA))
      self$`invitee_email` <- ApiClient$new()$deserializeObj(InvitationOrganizationJoinEmailObject$`invitee_email`, "array[character]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

