# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvitationArrayShareEmail
#'
#' @description InvitationArrayShareEmail Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field actions  list( \link{ArrayActions} ) 
#'
#' @field invitee_email  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvitationArrayShareEmail <- R6::R6Class(
  'InvitationArrayShareEmail',
  public = list(
    `actions` = NULL,
    `invitee_email` = NULL,
    initialize = function(
        `actions`, `invitee_email`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`actions`)) {
        stopifnot(is.vector(`actions`), length(`actions`) != 0)
        sapply(`actions`, function(x) stopifnot(R6::is.R6(x)))
        self$`actions` <- `actions`
      }
      if (!missing(`invitee_email`)) {
        stopifnot(is.vector(`invitee_email`), length(`invitee_email`) != 0)
        sapply(`invitee_email`, function(x) stopifnot(is.character(x)))
        self$`invitee_email` <- `invitee_email`
      }
    },
    toJSON = function() {
      InvitationArrayShareEmailObject <- list()
      if (!is.null(self$`actions`)) {
        InvitationArrayShareEmailObject[['actions']] <-
          lapply(self$`actions`, function(x) x$toJSON())
      }
      if (!is.null(self$`invitee_email`)) {
        InvitationArrayShareEmailObject[['invitee_email']] <-
          self$`invitee_email`
      }

      InvitationArrayShareEmailObject
    },
    fromJSON = function(InvitationArrayShareEmailJson) {
      InvitationArrayShareEmailObject <- jsonlite::fromJSON(InvitationArrayShareEmailJson)
      if (!is.null(InvitationArrayShareEmailObject$`actions`)) {
        self$`actions` <- ApiClient$new()$deserializeObj(InvitationArrayShareEmailObject$`actions`, "array[ArrayActions]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(InvitationArrayShareEmailObject$`invitee_email`)) {
        self$`invitee_email` <- ApiClient$new()$deserializeObj(InvitationArrayShareEmailObject$`invitee_email`, "array[character]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`actions`)) {
        sprintf(
        '"actions":
        [%s]
',
        paste(sapply(self$`actions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`invitee_email`)) {
        sprintf(
        '"invitee_email":
           [%s]
        ',
        paste(unlist(lapply(self$`invitee_email`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvitationArrayShareEmailJson) {
      InvitationArrayShareEmailObject <- jsonlite::fromJSON(InvitationArrayShareEmailJson)
      self$`actions` <- ApiClient$new()$deserializeObj(InvitationArrayShareEmailObject$`actions`, "array[ArrayActions]", loadNamespace("tiledbcloud"))
      self$`invitee_email` <- ApiClient$new()$deserializeObj(InvitationArrayShareEmailObject$`invitee_email`, "array[character]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

