# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ReadState
#'
#' @description ReadState Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field initialized  character [optional]
#'
#' @field overflowed  character [optional]
#'
#' @field unsplittable  character [optional]
#'
#' @field subarrayPartitioner  \link{SubarrayPartitioner} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ReadState <- R6::R6Class(
  'ReadState',
  public = list(
    `initialized` = NULL,
    `overflowed` = NULL,
    `unsplittable` = NULL,
    `subarrayPartitioner` = NULL,
    initialize = function(
        `initialized`=NULL, `overflowed`=NULL, `unsplittable`=NULL, `subarrayPartitioner`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`initialized`)) {
        self$`initialized` <- `initialized`
      }
      if (!is.null(`overflowed`)) {
        self$`overflowed` <- `overflowed`
      }
      if (!is.null(`unsplittable`)) {
        self$`unsplittable` <- `unsplittable`
      }
      if (!is.null(`subarrayPartitioner`)) {
        stopifnot(R6::is.R6(`subarrayPartitioner`))
        self$`subarrayPartitioner` <- `subarrayPartitioner`
      }
    },
    toJSON = function() {
      ReadStateObject <- list()
      if (!is.null(self$`initialized`)) {
        ReadStateObject[['initialized']] <-
          self$`initialized`
      }
      if (!is.null(self$`overflowed`)) {
        ReadStateObject[['overflowed']] <-
          self$`overflowed`
      }
      if (!is.null(self$`unsplittable`)) {
        ReadStateObject[['unsplittable']] <-
          self$`unsplittable`
      }
      if (!is.null(self$`subarrayPartitioner`)) {
        ReadStateObject[['subarrayPartitioner']] <-
          self$`subarrayPartitioner`$toJSON()
      }

      ReadStateObject
    },
    fromJSON = function(ReadStateJson) {
      ReadStateObject <- jsonlite::fromJSON(ReadStateJson)
      if (!is.null(ReadStateObject$`initialized`)) {
        self$`initialized` <- ReadStateObject$`initialized`
      }
      if (!is.null(ReadStateObject$`overflowed`)) {
        self$`overflowed` <- ReadStateObject$`overflowed`
      }
      if (!is.null(ReadStateObject$`unsplittable`)) {
        self$`unsplittable` <- ReadStateObject$`unsplittable`
      }
      if (!is.null(ReadStateObject$`subarrayPartitioner`)) {
        subarrayPartitionerObject <- SubarrayPartitioner$new()
        subarrayPartitionerObject$fromJSON(jsonlite::toJSON(ReadStateObject$subarrayPartitioner, auto_unbox = TRUE, digits = NA))
        self$`subarrayPartitioner` <- subarrayPartitionerObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`initialized`)) {
        sprintf(
        '"initialized":
          "%s"
                ',
        self$`initialized`
        )},
        if (!is.null(self$`overflowed`)) {
        sprintf(
        '"overflowed":
          "%s"
                ',
        self$`overflowed`
        )},
        if (!is.null(self$`unsplittable`)) {
        sprintf(
        '"unsplittable":
          "%s"
                ',
        self$`unsplittable`
        )},
        if (!is.null(self$`subarrayPartitioner`)) {
        sprintf(
        '"subarrayPartitioner":
        %s
        ',
        jsonlite::toJSON(self$`subarrayPartitioner`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ReadStateJson) {
      ReadStateObject <- jsonlite::fromJSON(ReadStateJson)
      self$`initialized` <- ReadStateObject$`initialized`
      self$`overflowed` <- ReadStateObject$`overflowed`
      self$`unsplittable` <- ReadStateObject$`unsplittable`
      self$`subarrayPartitioner` <- SubarrayPartitioner$new()$fromJSON(jsonlite::toJSON(ReadStateObject$subarrayPartitioner, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

