# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SQLParameters
#'
#' @description SQLParameters Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field query  character [optional]
#'
#' @field output_uri  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SQLParameters <- R6::R6Class(
  'SQLParameters',
  public = list(
    `name` = NULL,
    `query` = NULL,
    `output_uri` = NULL,
    initialize = function(
        `name`=NULL, `query`=NULL, `output_uri`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`query`)) {
        stopifnot(is.character(`query`), length(`query`) == 1)
        self$`query` <- `query`
      }
      if (!is.null(`output_uri`)) {
        stopifnot(is.character(`output_uri`), length(`output_uri`) == 1)
        self$`output_uri` <- `output_uri`
      }
    },
    toJSON = function() {
      SQLParametersObject <- list()
      if (!is.null(self$`name`)) {
        SQLParametersObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`query`)) {
        SQLParametersObject[['query']] <-
          self$`query`
      }
      if (!is.null(self$`output_uri`)) {
        SQLParametersObject[['output_uri']] <-
          self$`output_uri`
      }

      SQLParametersObject
    },
    fromJSON = function(SQLParametersJson) {
      SQLParametersObject <- jsonlite::fromJSON(SQLParametersJson)
      if (!is.null(SQLParametersObject$`name`)) {
        self$`name` <- SQLParametersObject$`name`
      }
      if (!is.null(SQLParametersObject$`query`)) {
        self$`query` <- SQLParametersObject$`query`
      }
      if (!is.null(SQLParametersObject$`output_uri`)) {
        self$`output_uri` <- SQLParametersObject$`output_uri`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`query`)) {
        sprintf(
        '"query":
          "%s"
                ',
        self$`query`
        )},
        if (!is.null(self$`output_uri`)) {
        sprintf(
        '"output_uri":
          "%s"
                ',
        self$`output_uri`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SQLParametersJson) {
      SQLParametersObject <- jsonlite::fromJSON(SQLParametersJson)
      self$`name` <- SQLParametersObject$`name`
      self$`query` <- SQLParametersObject$`query`
      self$`output_uri` <- SQLParametersObject$`output_uri`
      self
    }
  )
)

