# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SubarrayPartitionerState
#'
#' @description SubarrayPartitionerState Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field start  integer [optional]
#'
#' @field end  integer [optional]
#'
#' @field singleRange  list( \link{Subarray} ) [optional]
#'
#' @field multiRange  list( \link{Subarray} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SubarrayPartitionerState <- R6::R6Class(
  'SubarrayPartitionerState',
  public = list(
    `start` = NULL,
    `end` = NULL,
    `singleRange` = NULL,
    `multiRange` = NULL,
    initialize = function(
        `start`=NULL, `end`=NULL, `singleRange`=NULL, `multiRange`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`start`)) {
        stopifnot(is.numeric(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!is.null(`end`)) {
        stopifnot(is.numeric(`end`), length(`end`) == 1)
        self$`end` <- `end`
      }
      if (!is.null(`singleRange`)) {
        stopifnot(is.vector(`singleRange`), length(`singleRange`) != 0)
        sapply(`singleRange`, function(x) stopifnot(R6::is.R6(x)))
        self$`singleRange` <- `singleRange`
      }
      if (!is.null(`multiRange`)) {
        stopifnot(is.vector(`multiRange`), length(`multiRange`) != 0)
        sapply(`multiRange`, function(x) stopifnot(R6::is.R6(x)))
        self$`multiRange` <- `multiRange`
      }
    },
    toJSON = function() {
      SubarrayPartitionerStateObject <- list()
      if (!is.null(self$`start`)) {
        SubarrayPartitionerStateObject[['start']] <-
          self$`start`
      }
      if (!is.null(self$`end`)) {
        SubarrayPartitionerStateObject[['end']] <-
          self$`end`
      }
      if (!is.null(self$`singleRange`)) {
        SubarrayPartitionerStateObject[['singleRange']] <-
          lapply(self$`singleRange`, function(x) x$toJSON())
      }
      if (!is.null(self$`multiRange`)) {
        SubarrayPartitionerStateObject[['multiRange']] <-
          lapply(self$`multiRange`, function(x) x$toJSON())
      }

      SubarrayPartitionerStateObject
    },
    fromJSON = function(SubarrayPartitionerStateJson) {
      SubarrayPartitionerStateObject <- jsonlite::fromJSON(SubarrayPartitionerStateJson)
      if (!is.null(SubarrayPartitionerStateObject$`start`)) {
        self$`start` <- SubarrayPartitionerStateObject$`start`
      }
      if (!is.null(SubarrayPartitionerStateObject$`end`)) {
        self$`end` <- SubarrayPartitionerStateObject$`end`
      }
      if (!is.null(SubarrayPartitionerStateObject$`singleRange`)) {
        self$`singleRange` <- ApiClient$new()$deserializeObj(SubarrayPartitionerStateObject$`singleRange`, "array[Subarray]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(SubarrayPartitionerStateObject$`multiRange`)) {
        self$`multiRange` <- ApiClient$new()$deserializeObj(SubarrayPartitionerStateObject$`multiRange`, "array[Subarray]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`start`)) {
        sprintf(
        '"start":
          %d
                ',
        self$`start`
        )},
        if (!is.null(self$`end`)) {
        sprintf(
        '"end":
          %d
                ',
        self$`end`
        )},
        if (!is.null(self$`singleRange`)) {
        sprintf(
        '"singleRange":
        [%s]
',
        paste(sapply(self$`singleRange`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`multiRange`)) {
        sprintf(
        '"multiRange":
        [%s]
',
        paste(sapply(self$`multiRange`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SubarrayPartitionerStateJson) {
      SubarrayPartitionerStateObject <- jsonlite::fromJSON(SubarrayPartitionerStateJson)
      self$`start` <- SubarrayPartitionerStateObject$`start`
      self$`end` <- SubarrayPartitionerStateObject$`end`
      self$`singleRange` <- ApiClient$new()$deserializeObj(SubarrayPartitionerStateObject$`singleRange`, "array[Subarray]", loadNamespace("tiledbcloud"))
      self$`multiRange` <- ApiClient$new()$deserializeObj(SubarrayPartitionerStateObject$`multiRange`, "array[Subarray]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

