# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TaskGraphLogsData
#'
#' @description TaskGraphLogsData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field task_graph_logs  list( \link{TaskGraphLog} ) [optional]
#'
#' @field pagination_metadata  \link{PaginationMetadata} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TaskGraphLogsData <- R6::R6Class(
  'TaskGraphLogsData',
  public = list(
    `task_graph_logs` = NULL,
    `pagination_metadata` = NULL,
    initialize = function(
        `task_graph_logs`=NULL, `pagination_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`task_graph_logs`)) {
        stopifnot(is.vector(`task_graph_logs`), length(`task_graph_logs`) != 0)
        sapply(`task_graph_logs`, function(x) stopifnot(R6::is.R6(x)))
        self$`task_graph_logs` <- `task_graph_logs`
      }
      if (!is.null(`pagination_metadata`)) {
        stopifnot(R6::is.R6(`pagination_metadata`))
        self$`pagination_metadata` <- `pagination_metadata`
      }
    },
    toJSON = function() {
      TaskGraphLogsDataObject <- list()
      if (!is.null(self$`task_graph_logs`)) {
        TaskGraphLogsDataObject[['task_graph_logs']] <-
          lapply(self$`task_graph_logs`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination_metadata`)) {
        TaskGraphLogsDataObject[['pagination_metadata']] <-
          self$`pagination_metadata`$toJSON()
      }

      TaskGraphLogsDataObject
    },
    fromJSON = function(TaskGraphLogsDataJson) {
      TaskGraphLogsDataObject <- jsonlite::fromJSON(TaskGraphLogsDataJson)
      if (!is.null(TaskGraphLogsDataObject$`task_graph_logs`)) {
        self$`task_graph_logs` <- ApiClient$new()$deserializeObj(TaskGraphLogsDataObject$`task_graph_logs`, "array[TaskGraphLog]", loadNamespace("tiledbcloud"))
      }
      if (!is.null(TaskGraphLogsDataObject$`pagination_metadata`)) {
        pagination_metadataObject <- PaginationMetadata$new()
        pagination_metadataObject$fromJSON(jsonlite::toJSON(TaskGraphLogsDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
        self$`pagination_metadata` <- pagination_metadataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`task_graph_logs`)) {
        sprintf(
        '"task_graph_logs":
        [%s]
',
        paste(sapply(self$`task_graph_logs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination_metadata`)) {
        sprintf(
        '"pagination_metadata":
        %s
        ',
        jsonlite::toJSON(self$`pagination_metadata`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TaskGraphLogsDataJson) {
      TaskGraphLogsDataObject <- jsonlite::fromJSON(TaskGraphLogsDataJson)
      self$`task_graph_logs` <- ApiClient$new()$deserializeObj(TaskGraphLogsDataObject$`task_graph_logs`, "array[TaskGraphLog]", loadNamespace("tiledbcloud"))
      self$`pagination_metadata` <- PaginationMetadata$new()$fromJSON(jsonlite::toJSON(TaskGraphLogsDataObject$pagination_metadata, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

