# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.0.4
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UDFInfoVersion
#'
#' @description UDFInfoVersion Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field udf_image_uuid  character [optional]
#'
#' @field name  character [optional]
#'
#' @field version  character [optional]
#'
#' @field image_name  character [optional]
#'
#' @field exec  character [optional]
#'
#' @field exec_raw  character [optional]
#'
#' @field default  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UDFInfoVersion <- R6::R6Class(
  'UDFInfoVersion',
  public = list(
    `id` = NULL,
    `udf_image_uuid` = NULL,
    `name` = NULL,
    `version` = NULL,
    `image_name` = NULL,
    `exec` = NULL,
    `exec_raw` = NULL,
    `default` = NULL,
    initialize = function(
        `id`=NULL, `udf_image_uuid`=NULL, `name`=NULL, `version`=NULL, `image_name`=NULL, `exec`=NULL, `exec_raw`=NULL, `default`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`udf_image_uuid`)) {
        stopifnot(is.character(`udf_image_uuid`), length(`udf_image_uuid`) == 1)
        self$`udf_image_uuid` <- `udf_image_uuid`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`image_name`)) {
        stopifnot(is.character(`image_name`), length(`image_name`) == 1)
        self$`image_name` <- `image_name`
      }
      if (!is.null(`exec`)) {
        stopifnot(is.character(`exec`), length(`exec`) == 1)
        self$`exec` <- `exec`
      }
      if (!is.null(`exec_raw`)) {
        stopifnot(is.character(`exec_raw`), length(`exec_raw`) == 1)
        self$`exec_raw` <- `exec_raw`
      }
      if (!is.null(`default`)) {
        self$`default` <- `default`
      }
    },
    toJSON = function() {
      UDFInfoVersionObject <- list()
      if (!is.null(self$`id`)) {
        UDFInfoVersionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`udf_image_uuid`)) {
        UDFInfoVersionObject[['udf_image_uuid']] <-
          self$`udf_image_uuid`
      }
      if (!is.null(self$`name`)) {
        UDFInfoVersionObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`version`)) {
        UDFInfoVersionObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`image_name`)) {
        UDFInfoVersionObject[['image_name']] <-
          self$`image_name`
      }
      if (!is.null(self$`exec`)) {
        UDFInfoVersionObject[['exec']] <-
          self$`exec`
      }
      if (!is.null(self$`exec_raw`)) {
        UDFInfoVersionObject[['exec_raw']] <-
          self$`exec_raw`
      }
      if (!is.null(self$`default`)) {
        UDFInfoVersionObject[['default']] <-
          self$`default`
      }

      UDFInfoVersionObject
    },
    fromJSON = function(UDFInfoVersionJson) {
      UDFInfoVersionObject <- jsonlite::fromJSON(UDFInfoVersionJson)
      if (!is.null(UDFInfoVersionObject$`id`)) {
        self$`id` <- UDFInfoVersionObject$`id`
      }
      if (!is.null(UDFInfoVersionObject$`udf_image_uuid`)) {
        self$`udf_image_uuid` <- UDFInfoVersionObject$`udf_image_uuid`
      }
      if (!is.null(UDFInfoVersionObject$`name`)) {
        self$`name` <- UDFInfoVersionObject$`name`
      }
      if (!is.null(UDFInfoVersionObject$`version`)) {
        self$`version` <- UDFInfoVersionObject$`version`
      }
      if (!is.null(UDFInfoVersionObject$`image_name`)) {
        self$`image_name` <- UDFInfoVersionObject$`image_name`
      }
      if (!is.null(UDFInfoVersionObject$`exec`)) {
        self$`exec` <- UDFInfoVersionObject$`exec`
      }
      if (!is.null(UDFInfoVersionObject$`exec_raw`)) {
        self$`exec_raw` <- UDFInfoVersionObject$`exec_raw`
      }
      if (!is.null(UDFInfoVersionObject$`default`)) {
        self$`default` <- UDFInfoVersionObject$`default`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`udf_image_uuid`)) {
        sprintf(
        '"udf_image_uuid":
          "%s"
                ',
        self$`udf_image_uuid`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          "%s"
                ',
        self$`version`
        )},
        if (!is.null(self$`image_name`)) {
        sprintf(
        '"image_name":
          "%s"
                ',
        self$`image_name`
        )},
        if (!is.null(self$`exec`)) {
        sprintf(
        '"exec":
          "%s"
                ',
        self$`exec`
        )},
        if (!is.null(self$`exec_raw`)) {
        sprintf(
        '"exec_raw":
          "%s"
                ',
        self$`exec_raw`
        )},
        if (!is.null(self$`default`)) {
        sprintf(
        '"default":
          "%s"
                ',
        self$`default`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UDFInfoVersionJson) {
      UDFInfoVersionObject <- jsonlite::fromJSON(UDFInfoVersionJson)
      self$`id` <- UDFInfoVersionObject$`id`
      self$`udf_image_uuid` <- UDFInfoVersionObject$`udf_image_uuid`
      self$`name` <- UDFInfoVersionObject$`name`
      self$`version` <- UDFInfoVersionObject$`version`
      self$`image_name` <- UDFInfoVersionObject$`image_name`
      self$`exec` <- UDFInfoVersionObject$`exec`
      self$`exec_raw` <- UDFInfoVersionObject$`exec_raw`
      self$`default` <- UDFInfoVersionObject$`default`
      self
    }
  )
)

