# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UDFArrayDetails
#'
#' @description UDFArrayDetails Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field uri  character [optional]
#'
#' @field ranges  \link{QueryRanges} [optional]
#'
#' @field buffers  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UDFArrayDetails <- R6::R6Class(
  'UDFArrayDetails',
  public = list(
    `uri` = NULL,
    `ranges` = NULL,
    `buffers` = NULL,
    initialize = function(
        `uri`=NULL, `ranges`=NULL, `buffers`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!is.null(`ranges`)) {
        stopifnot(R6::is.R6(`ranges`))
        self$`ranges` <- `ranges`
      }
      if (!is.null(`buffers`)) {
        stopifnot(is.vector(`buffers`), length(`buffers`) != 0)
        sapply(`buffers`, function(x) stopifnot(is.character(x)))
        self$`buffers` <- `buffers`
      }
    },
    toJSON = function() {
      UDFArrayDetailsObject <- list()
      if (!is.null(self$`uri`)) {
        UDFArrayDetailsObject[['uri']] <-
          self$`uri`
      }
      if (!is.null(self$`ranges`)) {
        UDFArrayDetailsObject[['ranges']] <-
          self$`ranges`$toJSON()
      }
      if (!is.null(self$`buffers`)) {
        UDFArrayDetailsObject[['buffers']] <-
          self$`buffers`
      }

      UDFArrayDetailsObject
    },
    fromJSON = function(UDFArrayDetailsJson) {
      UDFArrayDetailsObject <- jsonlite::fromJSON(UDFArrayDetailsJson)
      if (!is.null(UDFArrayDetailsObject$`uri`)) {
        self$`uri` <- UDFArrayDetailsObject$`uri`
      }
      if (!is.null(UDFArrayDetailsObject$`ranges`)) {
        rangesObject <- QueryRanges$new()
        rangesObject$fromJSON(jsonlite::toJSON(UDFArrayDetailsObject$ranges, auto_unbox = TRUE, digits = NA))
        self$`ranges` <- rangesObject
      }
      if (!is.null(UDFArrayDetailsObject$`buffers`)) {
        self$`buffers` <- ApiClient$new()$deserializeObj(UDFArrayDetailsObject$`buffers`, "array[character]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`uri`)) {
        sprintf(
        '"uri":
          "%s"
                ',
        self$`uri`
        )},
        if (!is.null(self$`ranges`)) {
        sprintf(
        '"ranges":
        %s
        ',
        jsonlite::toJSON(self$`ranges`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`buffers`)) {
        sprintf(
        '"buffers":
           [%s]
        ',
        paste(unlist(lapply(self$`buffers`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UDFArrayDetailsJson) {
      UDFArrayDetailsObject <- jsonlite::fromJSON(UDFArrayDetailsJson)
      self$`uri` <- UDFArrayDetailsObject$`uri`
      self$`ranges` <- QueryRanges$new()$fromJSON(jsonlite::toJSON(UDFArrayDetailsObject$ranges, auto_unbox = TRUE, digits = NA))
      self$`buffers` <- ApiClient$new()$deserializeObj(UDFArrayDetailsObject$`buffers`, "array[character]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

