# Run CI for R based on copy of https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  TILEDB_REST_TOKEN_UNITTEST: ${{ secrets.TILEDB_REST_TOKEN_UNITTEST }}
  
jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: ./r-ci.sh bootstrap

      - name: Dependencies
        run: ./r-ci.sh install_deps

      - name: Test
        run: ./r-ci.sh run_tests
